### ISSUE TITLE
Load event firing infinitely

### ISSUE THREAD

**Issue by cecasey** [imgix/angular#231]
When using `(load)` with IxImgComponent, a load event is fired infinitely.

`<img (load)="onLoad()" ixImg path="abc" alt="">`

- @imgix/angular version: 1.1.6
- Angular version: 12.1
- Rendering Engine - Ivy

**Comment by frederickfogerty** [comment]
Hi @cecasey 👋  thanks for opening this issue. I've put this on my schedule to investigate next week. I'll provide any updates here.
