### ISSUE TITLE
Angular Dependency Upgrade 13/14

### ISSUE THREAD

**Issue by lcottingham** [imgix/angular#272]
Please provide the following information and someone from @imgix/imgix-sdk-team will respond to your issue shortly.

**Before you submit:**

- [x] Please search through the [existing issues](https://github.com/imgix/angular/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your feature has already been discussed.
- [x] Please take a moment to find out whether your idea fits with the scope and aims of this project.

**Is your feature request related to a problem? Please describe.**
Peer dependency locked to angular ^12 causes `npm install` to fail for all node 7+ versions. The only workaround is to ignore this dependency conflict with `npm install --legacy-peer-deps`. The library seems to work fine when forcefully installed into angular 13 and 14 versions, so it should be a simple version bump.

**Describe the solution you'd like**
Bump angular dependencies to support angular 13.x and 14.x

**Describe alternatives you've considered**
Running install with `--legacy-peer-deps` works

**Comment by sherwinski** [comment]
Hey @lcottingham thanks for calling this out. This was something our team was planning to look into more but we appreciate the assist on testing this out on newer angular versions. 

We'd happily accept a PR to adjust the peer dependencies if that's something you'd be interested in; otherwise someone from our team will get to it when we can carve out some time for it.

**Comment by atlawrie** [comment]
Hi @lcottingham, we went ahead and migrated the library from Angular 12 to Angular 13. We’ve confirmed this allows installation without --legacy-peer-deps through npm. This was rolled out for release in 1.1.10. No user-facing functionality has changed, so you should be able to continue to use it as is in your project with no problems.

**Comment by lcottingham** [comment]
Fantastic! Sorry, I didn't get a chance to send a PR, but great we got it all resolved.
